LANG = {
    "English": {
        "title": "💧 Water Issue Tracker - Civic System",
        "menu": "Menu",
        "dashboard": "🏠 Dashboard",
        "report": "📢 Report Issue",
        "view": "📋 View Complaints",
        "admin": "🛠 Admin Panel",
        "total": "Total Complaints",
        "pending": "Pending",
        "resolved": "Resolved",
        "report_title": "Citizen AI Complaint System",
        "citizen_ai": "Citizen AI Complaint",
        "admin_dashboard": "Admin Dashboard",
        "name": "Name",
        "phone": "Phone",
        "problem_explain": "Describe the water problem",
        "upload_evidence": "Upload Evidence",
        "analyze_complaint": "🤖 Analyze Complaint",
        "submit": "Submit Complaint",
        "success": "Complaint Submitted",
        "fill_required": "Fill required fields",
        "invalid_phone": "Invalid Phone",
        "view_details": "View Details",
        "citizen_proof": "Citizen Proof",
        "resolution_details": "Resolution Details",
        "resolution_proof": "Upload Resolution Proof",
        "admin_password": "Admin Password",
        "admin_success": "Admin Login Successful",
        "status": "Status",
        "complaint_index": "Complaint Index",
        "selected_issue": "Selected Issue:",
        "current_status": "Current Status:",
        "update": "Update Complaint",
        "wrong": "Wrong Password",
        "ai_mode": "AI Mode",
        "local_ai": "Local AI Inference (Ollama)",
        "byok_ai": "BYOK (OpenAI token)",
        "api_key": "Enter API Token",
        "issue_type": "Issue Type",
        "location": "Location",
        "priority": "Priority",
        "description": "Description",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "emergency": "Emergency",
        "ai_result": "AI Analysis Result",
        "ai_solution": "AI Suggested Solution",
        "ai_suggest_solution": "AI Suggest Solution",
        "ai_status": "AI Status",
        "progress": "Progress",
        "estimated_completion": "Estimated Completion",
        "ai_updates": "AI Updates",
        "admin_solution": "Admin Solution",
        "final_ai_report": "Final AI Report",
        "fill_api_key": "Enter API key for BYOK mode",
        "ai_status_initial": "AI complaint triage in progress",
        "ai_updates_initial": "AI analysis started",
        "help": "🆘 Help Desk",
        "help_title": "Help Desk and AI Support",
        "help_description": "Ask for help about complaint submission, AI analysis, or the tracker workflow.",
        "support_contact": "For urgent issues, contact your local water authority.",
        "help_chat_prompt": "Type your question here...",
        "help_submit": "Submit Help Request",
        "help_response": "Help Desk Response",
        "possible_cause": "Possible Cause",
        "repair_steps": "Repair Steps",
        "department": "Department",
        "urgency": "Estimated Urgency",
        "no_complaints": "No complaints available",
        "no_complaints_map": "No complaints available for mapping.",
        "no_locations": "No valid locations could be plotted.",
    },
    "తెలుగు": {
        "title": "💧 నీటి సమస్య ట్రాకర్",
        "menu": "మెనూ",
        "dashboard": "🏠 డాష్‌బోర్డ్",
        "report": "📢 సమస్య తెలియజేయండి",
        "view": "📋 ఫిర్యాదులు చూడండి",
        "admin": "🛠 అడ్మిన్ ప్యానల్",
        "total": "మొత్తం ఫిర్యాదులు",
        "pending": "పెండింగ్",
        "resolved": "పరిష్కరించబడింది",
        "report_title": "నాగరిక AI ఫిర్యాదు సిస్టమ్",
        "citizen_ai": "నాగరిక AI ఫిర్యాదు",
        "admin_dashboard": "నిర్వాహక డ్యాష్‌బోర్డ్",
        "name": "పేరు",
        "phone": "ఫోన్",
        "problem_explain": "నీటి సమస్యను వివరించండి",
        "upload_evidence": "సాక్ష్యాన్ని అప్లోడ్ చేయండి",
        "analyze_complaint": "🤖 ఫిర్యాదును విశ్లేషించండి",
        "submit": "ఫిర్యాదును పంపండి",
        "success": "ఫిర్యాదు సమర్పించారు",
        "fill_required": "అవసరమైన ఫీల్డ్స్ నింపండి",
        "invalid_phone": "చెల్లని ఫోన్",
        "view_details": "వివరాలు చూడండి",
        "citizen_proof": "నాగరిక ఆధారాలు",
        "resolution_details": "పరిష్కార వివరాలు",
        "resolution_proof": "పరిష్కార ఆధారాన్ని అప్లోడ్ చేయండి",
        "admin_password": "నిర్వాహక పాస్‌వర్డ్",
        "admin_success": "నిర్వాహక లాగిన్ విజయవంతం",
        "status": "స్థితి",
        "complaint_index": "ఫిర్యాది సూచిక",
        "selected_issue": "ఎంచుకున్న సమస్య:",
        "current_status": "ప్రస్తుత స్థితి:",
        "update": "ఫిర్యాదును నవీకరించండి",
        "wrong": "తప్పు పాస్‌వర్డ్",
        "ai_mode": "AI మోడ్",
        "local_ai": "స్థానిక AI (Ollama)",
        "byok_ai": "BYOK (OpenAI టోకెన్)",
        "api_key": "API టోకన్ని నమోదు చేయండి",
        "issue_type": "సమస్య రకం",
        "location": "స్థానం",
        "priority": "ప్రాధాన్యం",
        "description": "వివరణ",
        "low": "తక్కువ",
        "medium": "మధ్యస్థ",
        "high": "ఎత్తైన",
        "emergency": "తాత్కాలిక",
        "ai_result": "AI విశ్లేషణ ఫలితం",
        "ai_solution": "AI సూచించిన పరిష్కారం",
        "ai_suggest_solution": "AI పరిష్కారం సూచించు",
        "possible_cause": "సంభవించే కారణం",
        "repair_steps": "పరిద్ధరణ దశలు",
        "department": "శాఖ",
        "urgency": "అంచనా తీవ్రత",
        "no_complaints": "ఫిర్యాదులు లేవు",
        "no_complaints_map": "మ్యాపింగ్ కోసం ఫిర్యాదులు లేవు.",
        "no_locations": "చెల్లని స్థానాలను మ్యాప్ చేయలేకపోయాం.",
    },
    "हिन्दी": {
        "title": "💧 जल समस्या ट्रैकर",
        "menu": "मेनू",
        "dashboard": "🏠 डैशबोर्ड",
        "report": "📢 शिकायत दर्ज करें",
        "view": "📋 शिकायतें देखें",
        "admin": "🛠 प्रशासक पैनल",
        "total": "कुल शिकायतें",
        "pending": "बकाया",
        "resolved": "सुलझाई गई",
        "report_title": "नागरिक AI शिकायत प्रणाली",
        "citizen_ai": "नागरिक AI शिकायत",
        "admin_dashboard": "एडमिन डैशबोर्ड",
        "name": "नाम",
        "phone": "फोन",
        "problem_explain": "जल समस्या का विवरण दें",
        "upload_evidence": "सबूत अपलोड करें",
        "analyze_complaint": "🤖 शिकायत का विश्लेषण करें",
        "submit": "शिकायत जमा करें",
        "success": "शिकायत दर्ज की गई",
        "fill_required": "आवश्यक फ़ील्ड भरें",
        "invalid_phone": "अमान्य फ़ोन",
        "view_details": "विवरण देखें",
        "citizen_proof": "नागरिक प्रमाण",
        "resolution_details": "समाधान विवरण",
        "resolution_proof": "समाधान प्रमाण अपलोड करें",
        "admin_password": "एडमिन पासवर्ड",
        "admin_success": "एडमिन लॉगिन सफल",
        "status": "स्थिति",
        "complaint_index": "शिकायत सूचकांक",
        "selected_issue": "चयनित समस्या:",
        "current_status": "वर्तमान स्थिति:",
        "update": "शिकायत अपडेट करें",
        "wrong": "गलत पासवर्ड",
        "ai_mode": "AI मोड",
        "local_ai": "स्थानीय AI (Ollama)",
        "byok_ai": "BYOK (OpenAI टोकन)",
        "api_key": "API टोकन दर्ज करें",
        "issue_type": "समस्या प्रकार",
        "location": "स्थान",
        "priority": "प्राथमिकता",
        "description": "विवरण",
        "low": "कम",
        "medium": "मध्यम",
        "high": "उच्च",
        "emergency": "आपातकालीन",
        "ai_result": "AI विश्लेषण परिणाम",
        "ai_solution": "AI सुझाया गया समाधान",
        "ai_suggest_solution": "AI समाधान सुझाएं",
        "ai_status": "AI स्थिति",
        "progress": "प्रगति",
        "estimated_completion": "अनुमानित पूर्णता",
        "ai_updates": "AI अपडेट",
        "admin_solution": "एडमिन समाधान",
        "final_ai_report": "अंतिम AI रिपोर्ट",
        "fill_api_key": "BYOK मोड के लिए API कुंजी दर्ज करें",
        "ai_status_initial": "AI शिकायत ट्रायज प्रगति पर है",
        "ai_updates_initial": "AI विश्लेषण शुरू हुआ",
        "help": "🆘 हेल्प डेस्क",
        "help_title": "हेल्प डेस्क और AI समर्थन",
        "help_description": "शिकायत सबमिशन, AI विश्लेषण, या ट्रैकर वर्कफ़्लो के बारे में मदद के लिए पूछें।",
        "support_contact": "तत्काल मुद्दों के लिए, अपने स्थानीय जल प्राधिकरण से संपर्क करें।",
        "help_chat_prompt": "अपना प्रश्न यहां टाइप करें...",
        "help_submit": "हेल्प अनुरोध सबमिट करें",
        "help_response": "हेल्प डेस्क प्रतिक्रिया",
        "possible_cause": "संभावित कारण",
        "repair_steps": "मरम्मत चरण",
        "department": "विभाग",
        "urgency": "अनुमानित तात्कालिकता",
        "no_complaints": "कोई शिकायत नहीं है",
        "no_complaints_map": "मानचित्रण के लिए कोई शिकायत उपलब्ध नहीं है।",
        "no_locations": "कोई वैध स्थान मानचित्रित नहीं किया जा सका।",
    },
}
